name: .NET Master

on:
  push:
    branches: [ "master" ]

# master branch does a dotnet pack just to test the pipeline, without actually pushing anything to nuget.org.
# version numbers here do not matters.
env:
  VERSION_MAJOR: 0
  VERSION_MINOR: 0
  VERSION_SUFFIX: "-anything"

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Set Version variable
      id: version
      shell: bash
      run: echo "PRODUCT_VERSION=${{ env.VERSION_MAJOR }}.${{ env.VERSION_MINOR }}.$(date +'%Y%m%d').${{ github.run_attempt }}${{ env.VERSION_SUFFIX }}" >> $GITHUB_OUTPUT
    - uses: actions/checkout@v3
    - name: Setup .NET8
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Setup .NET10
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore SmartIOT.Connector.slnx
    - name: Build
      run: dotnet build -c Release --no-restore SmartIOT.Connector.slnx
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal SmartIOT.Connector.slnx
    - name: Pack
      run: dotnet pack -c Release /p:version=${{ steps.version.outputs.PRODUCT_VERSION }} SmartIOT.Connector.slnx
